#!/usr/bin/perl

# (c) 2015 Flexiant Limited
#
# This script will use the username and password generated by the foc-acronis-plugin to register
# an instalation of the Acronis linux agent with the FCO credentials.
#
# Input to this script will be the name of the acronis agent installer on your platform, for example linux_agent.bin.
# This script will then attempt a automatic instalation and registration use the FCO credentials.
#
# If you do not specify input for this script it will output the acronis url, username, and password used for registration.
#
# You will need to install XML XPath to use this script, libxml-xpath-perl.

use strict;
use warnings;
use XML::XPath;

my $metadataSource = "wget -q -O - http://169.254.169.254/metadata|";

my $acronisURL;         #CONFIG/meta/server/system/fco-acronis/url
my $acronisUsername;    #CONFIG/meta/server/system/fco-acronis/username
my $acronisPassword;    #CONFIG/meta/server/system/fco-acronis/password

my $agent = $ARGV[0] if ( $#ARGV >= 0 );

readMetadata();

if(defined($agent) and defined($acronisURL)){
	system ("./$agent -a -C $acronisURL -g $acronisUsername -w $acronisPassword");
}else{
	print STDERR "No agent file has been defined\n";
	if(defined($acronisURL)){
		print STDERR "Acronis Management URL $acronisURL\n";
		print STDERR "Acronis Username $acronisUsername\n";
		print STDERR "Acronis Password $acronisPassword\n";
	}else{
		print STDERR "No FCO/Acronis metadata found\n";
	}
}

sub readMetadata {
	my $count = 0;
	for ( ; ; sleep(1) ) {
		$count++;
		print STDERR "Waiting for network\n" if ( !( $count % 10 ) );

		return 0 if ( $count > 40 );

		open( XML, $metadataSource ) || next;
		my $xml = "";
		while (<XML>) {
			$xml .= $_;
		}
		close(XML);

		if ( $xml =~ /\s*</ ) {

			$xml =~ s/\s+\S+:\S+="\S*"//g;
	
			my $xPath = XML::XPath->new($xml);

			$acronisURL = $xPath->find("//CONFIG/meta/server/system/fco-acronis/url");
			$acronisUsername = $xPath->find("//CONFIG/meta/server/system/fco-acronis/username");
			$acronisPassword = $xPath->find("//CONFIG/meta/server/system/fco-acronis/password");
			
			return;
		}
	}
}
